name: Build Rust Package

on:
  push:
    branches:
      - main
    paths:
      - 'rust/gsea-rs/**'

jobs:
  build-rust-wasm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install wasm-pack
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
      - name: Build WASM package
        run: |
          cd rust/gsea-rs
          wasm-pack build --target web
      - name: Update Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: latest
          name: Latest Release
          files: |
            rust/gsea-rs/pkg/gsea_rs_bg.wasm
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
