name: Build Package

on:
  push:
    branches:
      - main
    paths:
      - 'gene_platform_utils/*.py'
      - 'pyproject.toml'
      - 'requirements.txt'
      - 'README.md'

jobs:
  build-package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - name: Install build dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build
      - name: Build package
        run: |
          python -m build
      - name: Update Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: latest
          name: Latest Release
          files: |
            dist/*.whl
            dist/*.tar.gz
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
